### ISSUE TITLE
after adding new item(barChord) unable to scroll open chord 

### ISSUE THREAD

**Issue by ricky-1529** [chRyNaN/GuitarChords#4] opened 2020-08-12 08:46 UTC
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 4(offset:4).state:11
[
![20200812_141903](https://user-images.githubusercontent.com/63810467/89994742-59f4fc00-dcaa-11ea-8d99-eeba68588b68.jpg)

**Comment by chRyNaN** [comment] 2020-08-12 17:21
Hi @ricky-1529 thanks for contributing! 

Unfortunately, I don't understand the issue you are having and it seems to be related to your code usage and not this library. A few things:
* If it's an issue with this library, then please provide more information (code in text, stacktrace, detailed reproduction steps).
* Instead of taking a screenshot, copy and paste the relevant code snippets. You can use [Github Markdown](https://guides.github.com/features/mastering-markdown/) to make it more legible.
* Provide details of the issue and reproduction steps when making an issue (I'll look into updating the bot to provide this as a reminder).

**Comment by ricky-1529** [comment] 2020-08-12 19:10
sorry it wasn't library issue. I just wanted to create more category below
"open string chords" title,  like ur sample app screenshot minor chords than major chords . but i can't mange with my little programming
knowledge. if u help me i will be grateful.

**Comment by chRyNaN** [comment] 2020-08-13 02:48
@ricky-1529 If you clone the repository and open it in Android Studio, you should be able to launch the sample module to a device and play around with it. And the `sample` module in the repository has all the sample app code you can reference.

Unfortunately I can't help with your application code. But don't be discouraged, keep trying and you will figure it out. There are forum websites, such as, Stackoverflow, where you can ask for assistance with programming. There are also plenty of resources online.

You are getting an `IndexOutOfBoundsException` which is probably due to accessing an index that exceeds the item count in the collection. If you are using an Android Adapter, it could be related to that code. Without further details its impossible for me to know. And again, I can't assist in application code.

I'm going to close this Issue, as these are meant for issues with the library itself. If you find an issue with the library, you can open another issue.

Good luck!

**Closed as completed by chRyNaN** 2020-08-13 02:48 UTC

**Comment by ricky-1529** [comment] 2020-08-13 04:33
Thank you for your time.

**Comment by ricky-1529** [comment] 2020-08-13 17:41
I have fixed all issues related my app. now updating chord library . Can I
use ur library on my app with proper credits? If u give me the permission.

**Comment by chRyNaN** [comment] 2020-08-13 23:36
@ricky-1529 good to hear! And yes you may use the library in accordance with the license (Apache 2.0). You do not have to ask for that since it is open source.

**Comment by ricky-1529** [comment] 2020-08-14 06:25
Thank you.

**Comment by ricky-1529** [comment] 2020-08-14 20:18
Last disturb,
after building bar chords it looks weird, is there any workaround. please
help

**Comment by cullub** [comment] 2020-08-18 14:21
@ricky-1529 If it looks weird, you likely did it wrong.  I can confirm that it does work beautifully if done right.  If you're interested in sample code, I used this library in my own personal project tabslite.com, which is open source.

**Comment by ricky-1529** [comment] 2020-08-18 19:01
Thank you so much.....
